In [1]:
#Implemenation of three selected models(LinearSVC, SVC, and Naive Bayes) for classifying of emotion using 
# StudEmo dataset 
# By Musa Adamu, 276780
# Bilal Abdulqader, 276789
# Shambhavi Sinha, 276867
# Oleksandr Yanchenkov, 276532

In [4]:
# some of the libraries used in the project
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

In [5]:
df_train = pd.read_excel('dataset/train.xlsx')
df_test = pd.read_excel('dataset/test.xlsx')
df_valid = pd.read_excel('dataset/valid.xlsx')

In [6]:
df_train.head()

,Unnamed: 0,text,joy_x,trust_x,anticipation_x,surprise_x,fear_x,sadness_x,disgust_x,anger_x,...,joy_y,trust_y,anticipation_y,surprise_y,fear_y,sadness_y,disgust_y,anger_y,valence_y,arousal_y
0,0,Cracow beautiful but hotel massacre . The serv...,0,0,0,0,0,0,2,0,...,0,0,0,0,0,0,2,0,-2,1
1,1,"b.good hotel for a business trip, swimming poo...",0,0,0,2,0,0,0,0,...,0,0,0,2,0,0,0,0,0,1
2,2,Opinion on the basis of the course II At the F...,2,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,2
3,3,"It's like Tefal, and China anyway. Water smell...",0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,2,2
4,4,"Hotel Solar is located on a slope, directly on...",1,0,1,0,0,0,0,0,...,1,0,1,0,0,0,0,0,2,1

In [31]:
df_test.head()

,Unnamed: 0,text,joy_x,trust_x,anticipation_x,surprise_x,fear_x,sadness_x,disgust_x,anger_x,...,joy_y,trust_y,anticipation_y,surprise_y,fear_y,sadness_y,disgust_y,anger_y,valence_y,arousal_y
0,2490,The reception is very friendly. The room is cl...,2,0,1,0,0,0,0,0,...,2,0,1,0,0,0,0,0,2,1
1,2491,She was thinking for a long time about the cho...,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
2,2492,"The staff is nice, parking next to the hotel, ...",2,1,0,0,0,0,0,1,...,2,1,2,0,0,0,0,0,2,1
3,2493,"More ! The lease expires in 36 years. In 1999,...",0,2,1,0,0,0,1,0,...,0,0,0,0,0,1,0,2,-1,1
4,2494,"""Not only does the intraocular pressure play a...",0,0,0,0,2,0,0,0,...,0,0,0,0,2,0,0,0,0,1

In [32]:
df_valid.head()

,Unnamed: 0,text,joy_x,trust_x,anticipation_x,surprise_x,fear_x,sadness_x,disgust_x,anger_x,...,joy_y,trust_y,anticipation_y,surprise_y,fear_y,sadness_y,disgust_y,anger_y,valence_y,arousal_y
0,2213,We stayed at the Hotel London for 4 days in la...,2,2,2,3,0,0,0,0,...,2,2,2,3,0,0,0,0,2,3
1,2214,"""The method developed by Maciej Wojtkowski (FD",0,0,0,0,0,0,0,0,...,1,2,3,2,0,0,0,0,2,2
2,2215,"Hello, 7 months ago I had the privilege of mee...",0,0,1,0,0,0,1,0,...,0,0,1,0,0,0,1,0,1,1
3,2216,Terrible food. I do not recommend ! Not comfor...,0,0,0,0,2,3,2,2,...,0,0,0,0,1,2,2,2,-2,0
4,2217,The photos contained in the hotel's advertisin...,2,1,1,0,0,0,0,0,...,2,1,1,0,0,0,0,0,2,1

In [8]:
print(f'Number of trained data: {len(df_train)}\nNumber of test data: {len(df_test)}\nNumber of valid data: {len(df_valid)}')

Number of trained data: 2212
Number of test data: 277
Number of valid data: 277

In [33]:
# converted emotion  score to their respective emotion labels such as joy, sadness, anticipation, 
# disgust etc as annoted by the annotators

In [9]:
train_data = pd.read_excel('dataset/train2.xlsx')
test_data = pd.read_excel('dataset/test3.xlsx')

In [35]:
train_data.head()

,Unnamed: 0,text,emotion_x,joy_x,trust_x,anticipation_x,surprise_x,fear_x,sadness_x,disgust_x,...,joy_y,trust_y,anticipation_y,surprise_y,fear_y,sadness_y,disgust_y,anger_y,valence_y,arousal_y
0,0,Cracow beautiful but hotel massacre . The serv...,Disgust,0,0,0,0,0,0,Disgust,...,0,0,0,0,0,0,Disgust,0,-2,1
1,1,"b.good hotel for a business trip, swimming poo...",Surprise,0,0,0,Surprise,0,0,0,...,0,0,0,Surprise,0,0,0,0,0,1
2,2,Opinion on the basis of the course II At the F...,Joy,Joy,0,0,0,0,0,0,...,Joy,0,0,0,0,0,0,0,0,2
3,3,"It's like Tefal, and China anyway. Water smell...",Anticipation,0,0,Anticipation,0,0,0,0,...,0,0,Anticipation,0,0,0,0,0,2,2
4,4,"Hotel Solar is located on a slope, directly on...",Joy Anticipation,Joy,0,Anticipation,0,0,0,0,...,Joy,0,Anticipation,0,0,0,0,0,2,1

In [36]:
test_data.head()

,Unnamed: 0,text,emotion_x,joy_x,trust_x,anticipation_x,surprise_x,fear_x,sadness_x,disgust_x,...,joy_y,trust_y,anticipation_y,surprise_y,fear_y,sadness_y,disgust_y,anger_y,valence_y,arousal_y
0,2490,The reception is very friendly. The room is cl...,Joy Anticipation,Joy,0,Anticipation,0,0,0,0,...,Joy,0,Anticipation,0,0,0,0,0,2,1
1,2491,She was thinking for a long time about the cho...,Disgust,0,0,0,0,0,0,Disgust,...,0,0,0,0,0,0,Disgust,0,0,1
2,2492,"The staff is nice, parking next to the hotel, ...",Joy Trust Anger,Joy,Trust,0,0,0,0,0,...,Joy,Trust,Anticipation,0,0,0,0,0,2,1
3,2493,"More ! The lease expires in 36 years. In 1999,...",Trust Anticipation Disgust,0,Trust,Anticipation,0,0,0,Disgust,...,0,0,0,0,0,Sadness,0,Anger,-1,1
4,2494,"""Not only does the intraocular pressure play a...",Fear,0,0,0,0,Fear,0,0,...,0,0,0,0,Fear,0,0,0,0,1

In [10]:
print(f'Number of trained data: {len(train_data)}\nNumber of test data: {len(test_data)}')

Number of trained data: 2212
Number of test data: 277

In [37]:
#Our models will be train and test based on the two columns that is text and emotion columns. 
# The text column will be converted into vector format

In [38]:

X_train = train_data['text']
y_train = train_data['emotion_x']
X_test = test_data['text']
y_test = test_data['emotion_x']

In [71]:
pipeline = Pipeline([
    ('vectorizer', TfidfVectorizer()),
    ('classifier', LinearSVC())
])

In [72]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', TfidfVectorizer()), ('classifier', LinearSVC())])

In [73]:
#training accuracy
train_accuracy = pipeline.score(X_train, y_train)
print('Accuracy:', train_accuracy)

Accuracy: 0.9977396021699819

In [74]:
test_accuracy = pipeline.score(X_test, y_test)
print('Accuracy:', test_accuracy)

Accuracy: 0.07942238267148015

In [43]:
# the second method which SVC will also be train using thesame column from the dataset

In [44]:
from sklearn.svm import SVC

In [45]:
vectorizer = TfidfVectorizer()

In [46]:
X = vectorizer.fit_transform(X_train)
Y = vectorizer.fit_transform(X_test)

In [91]:
clf = SVC(kernel='linear')
clf.fit(X, y_train)

SVC(kernel='linear')

In [59]:
#train accuracy
train_accuracy = clf.score(X, y_train)
print("Accuracy:", train_accuracy)

Accuracy: 0.6641048824593129

In [79]:
new_texts = ['Cracow beautiful but hotel massacre . The service wasnt nice all there dear to this ridiculous canteen on the ice rink you could kill yourself. . . And the swimming pool so much chlorine that there was nothing to breathe. . . The rooms lack words. . . . . . .we were afraid to bathe in the bathroom from the shower. . . And also TV 5 channels, 2 of them in Polish: ( I do NOT recommend! ! !', 'i am angry with you']
predictions = clf.predict(vectorizer.transform(new_texts))
print("Predictions:", predictions)

Predictions: ['  Trust Anticipation Surprise Sadness Disgust Anger'
 'Joy Trust Anticipation']

In [81]:
sample_texts = ['I have  been disappointed twice, The first time I was treated as an intruder wanting to get a visit from my husband, the doctor I called earlier and the doctor assured me that I would be accepted The second time I managed to get in, but I was not treated in the right direction. Generally, I was left with ailments that I was going to get rid of.']
predictions = clf.predict(vectorizer.transform(new_texts))
print("Predictions:", predictions)

Predictions: ['  Trust Anticipation Surprise Sadness Disgust Anger'
 'Joy Trust Anticipation']

In [ ]:
#method3 which is the naive bayes will also be trained using thesame column from the dataset

In [51]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [52]:
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [54]:
nb = MultinomialNB()
nb.fit(X_train_vec, y_train)

MultinomialNB()

In [57]:
#train accuracy
train_accuracy = nb.score(X_train_vec, y_train)
print("Accuracy: {:.2f}".format(train_accuracy))

Accuracy: 0.40

In [58]:
#test accuracy
test_accuracy = nb.score(X_test_vec, y_test)
print("Accuracy: {:.2f}".format(test_accuracy))

Accuracy: 0.10

In [ ]:
#Evaluation of some somple textual data across the trained classifiers and see how accurate they can
# predict the emotion

In [56]:
new_text = "I am feeling very happy today!"
new_text_vec = vectorizer.transform([new_text])
prediction = nb.predict(new_text_vec)[0]
print("Predicted emotion:", prediction)

Predicted emotion: Joy Trust Anticipation Surprise

In [88]:
sample_text = "Cracow beautiful, but hotel massacre. The service wasnt nice all there dear to this ridiculous canteen on the ice rink you could kill yourself, and the swimming pool so much chlorine that there was nothing to breathe. The rooms lack words. we were afraid to bathe in the bathroom from the shower. and also TV 5 channels, 2 of them in Polish: I do NOT recommend! 'i am angry with it/"
sample_text_vec = vectorizer.transform([sample_text])
prediction = nb.predict(sample_text_vec)[0]
print("Predicted emotion:", prediction)

Predicted emotion:   Trust

In [92]:
sample = ['I am feeling very happy today']
predictions = clf.predict(vectorizer.transform(sample))
print("Predictions:", predictions)

Predictions: ['Joy Trust Anticipation Surprise']

In [98]:
n = "then the tears come into my eyes, and it is just as if my mother kissed me"
n_text_vec = vectorizer.transform([n])
rediction = nb.predict(n_text_vec)[0]
print("Predicted emotion:", rediction)

Predicted emotion:   Fear Sadness Disgust Anger

In [99]:
s = ['then the tears come into my eyes, and it is just as if my mother kissed me']
prediction = clf.predict(vectorizer.transform(s))
print("Predictions:", prediction)

Predictions: ['  Fear Sadness']